### PR TITLE
Add 'gpmac' as option in --os

### PR DESCRIPTION
**Pull request by videlanicolas**
The --os option for mac needs to be Apple Mac OS X <some version> in order to be accepted by PaloAlto's Gateway. the option "gpmac" gives you that choice.

### CODE REVIEW

**Comment by dlenski** [comment]
Hmm… thanks for the feedback. (This probably isn't the right place to change the string, but that's easy to deal with.)

The *only* place that openconnect uses the OS Name is in the getconfig request string: https://github.com/dlenski/openconnect/blob/HEAD/gpst.c#L487-L492

Can you post a log showing what happens if you run `openconnect --dump -vvvv --prot=gp vpn.server.com` **without** this patch? I want to see where the failure occurs and what the message is.

**Comment by dlenski** [comment]
@rotx, you've also run this on a Mac. Have you had this problem.

**Comment by rotx** [comment]
No, I didn't have to specify that option (there are two other people at the office using this on a Mac and it works for them as well).

**Comment by dlenski** [comment]
Thanks, @rotx. That's what my testing has showed as well: my GP VPN doesn't seem to care what values I put in the `clientos` and `os-version` fields, as long as I put something.

@videlanicolas, your VPN might be configured in an unusual way to look at the values in the `os-version` fields and use them to set up the access profile differently. It'd be really helpful to see the `openconnect --dump -vvvv` logs with `platname="mac-intel"` compared to `platname="Apple Mac OS X 10.0.0.0"`.

**Comment by dlenski** [comment]
@videlanicolas, I am going to close this PR.

This is an issue which is worth fixing but…

* This isn't the right way to do it (we can easily change the string passed to GlobalProtect by `openconnect` running on a Mac without  requiring the user to input a special option)
* I need more information about the behavior with and without this option, as requested above, to ensure that it's going not going to cause problems for other users.

Please reopen if you can provide this.

**Pull request closed without merging**
