### PR TITLE
Add basic Docker support

### PR DESCRIPTION
**Pull request by andor-pierdelacabeza**
With this PR, I'mm adding basic Docker support, in the form of a Dockerfile, to allow running Openconnect inside a container, and certain portability.

Also, to avoid colission with a system installed Openconnect which may not have GlobalProtect support ;)

### CODE REVIEW

**Comment by dlenski** [comment]
See #44. My concern here is that I don't use Docker and don't know how to test if I've broken something in the Docker config in the repo.

Is it possible for you to add [tests of whether the docker build is working to the Travis-CI configuration](https://docs.travis-ci.com/user/docker/) so that I'd at least get some feedback that I've broken something?

**Comment by andor-pierdelacabeza** [comment]
Yep, we can at least test the docker build and maybe even run the binary, so we can check if all the dependencies are building correctly.

I don't have much expirience with Circle but I'll check it today or friday :ok_hand:

**Comment by andor-pierdelacabeza** [comment]
Sorry, I meant Travis :stuck_out_tongue:

**Comment by andor-pierdelacabeza** [comment]
:ok_hand: @dlenski , Does this look any better?

I've: 
- changed  the TravisCI yaml to make use of the new 'stages' feature
- named your build as 'App Build'
- added a new stage called 'Docker Build'

That new stage fully builds the container, runs it, runs `openconnect -V` inside of it, and looks for the string `gp`, so to confirm that GlobalProtect protocol support has been compiled in.

If `openconnect` fails to run or it doesn't find the string `gp`, the build will fail.

Future improvements may include doing a multistage build or changing it to 'alpine' distribution, to make it smaller and maybe faster to build. I'd like to test it slowly anyway, as alpine uses 'musl' instead of 'glib' and we might find some incompatibilities.

**Comment by dlenski** [comment]
@andor-pierdelacabeza, thanks! Sorry for not responding sooner. This version looks great, and I appreciate the thoughtful cleanups.

**Comment by andor-pierdelacabeza** [comment]
No prob, you're welcome! Let me know if you need anything else!
I'll ping my coworkers so they can test this with a client using Global Protect :)

**Pull request merged**
