### PR TITLE
teach globalprotect-challenge-login.py to accept prelogin cookies ins…

### PR DESCRIPTION
**Pull request by cizra**
…tead of passwords

### CODE REVIEW

**Comment by dlenski** [comment]
Thanks. So to make a long story short, the [login request](https://github.com/dlenski/openconnect/blob/globalprotect/PAN_GlobalProtect_protocol_doc.md#login-request) should fill in _either_ the `password` field _or_ the `prelogin-cookie` field, but not both, depending on which authentication mechanism is in use. (By the way, have you written a script to get the `prelogin-cookie` from the SAML authentication server as well?)

I could add a flag to the C code to accept a `prelogin-cookie` instead of a `password`, but it would probably be better if OpenConnect could _autodetect_ this situation.

Previously you mentioned something about the `/ssl-vpn/prelogin.esp` response. On all the VPNs I've seen, it just contains some generic blurb like this…

```xml
<prelogin-response>
<status>Success</status>
<ccusername/>
<autosubmit>false</autosubmit>
<msg/>
<license>yes</license>
<authentication-message>Enter login credentials</authentication-message>
<panos-version>1</panos-version>
<region>US</region>
</prelogin-response>```

… does the `prelogin` XML response contain some additional information on your VPN? If so, can you please post an obfuscated version of it?

**Comment by cizra** [comment]
> By the way, have you written a script to get the prelogin-cookie from the SAML authentication server as well?

Not yet. The login flow is much, much more complex than "put the password in this form field and make a POST".

> I could add a flag to the C code to accept a prelogin-cookie instead of a password, but it would probably be better if OpenConnect could autodetect this situation.

Not sure what OpenConnect does with password -- does it follow the same flow as `globalprotect-challenge-login.py`? I see no way to autodetect without actually trying to log in. OpenConnect wouldn't know whether to ask for passwd or prelogin-cookie. The user has to know what their VPN endpoint accepts.

> does the prelogin XML response contain some additional information on your VPN? If so, can you please post an obfuscated version of it?

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<prelogin-response>
<status>Success</status>
<ccusername></ccusername>
<autosubmit>false</autosubmit>
<msg></msg>
<newmsg></newmsg>
<license>yes</license>
<authentication-message>Enter login credentials</authentication-message>
<panos-version>1</panos-version><license-v6>yes</license-v6><saml-auth-status>0</saml-auth-status>
<saml-auth-method>REDIRECT</saml-auth-method>
<saml-request>base64-encoded URL to the login server</saml-request>
<region>2-letter country ISO code</region>
</prelogin-response>
```

**Comment by dlenski** [comment]
> Not sure what OpenConnect does with password -- does it follow the same flow as globalprotect-challenge-login.py?

Yep, this was just a throwaway script that I wrote when testing the 2FA login mechanism, since it's a whole lot faster to iterate changes in Python than in C.

> I see no way to autodetect without actually trying to log in. OpenConnect wouldn't know whether to ask for passwd or prelogin-cookie. The user has to know what their VPN endpoint accepts.

Right. My conjecture is that anytime the prelogin XML response contains `saml-auth-method`, the `prelogin-cookie` will be required, rather than the password.

> The login flow is much, much more complex than "put the password in this form field and make a POST".

Sounds like the SAML flow will never really be appropriate for incorporation into openconnect itself but… I'd like to make it as seamless as possible for a script to do the SAML auth and handoff the cookie to the openconnect binary.

After the SAML flow is complete, what form is the cookie delivered in?  Is it embedded in an HTML form which submits to `/ssl-vpn/login.esp`? Or does it show up in another way?

**Comment by dlenski** [comment]
Please see [this comment on #98](https://github.com/dlenski/openconnect/pull/98#issuecomment-380923571) and test my solution there. It will allow you to login to the gateway with the `prelogin-cookie` using the `openconnect` binary.

**Pull request closed without merging**
