### PR TITLE
README updates

### PR DESCRIPTION
**Pull request by 0atman**
- removed errent `
 - add libtool as an ubuntu dependency

### CODE REVIEW

**Comment by 0atman** [comment]
work in progress, I'll update when I've worked through all the missing documentation

**Comment by 0atman** [comment]
I had to faff with the vpnc-script, but as the error messages were clear in `./configure`, I don't think any readme updates are needed for that http://www.infradead.org/openconnect/vpnc-script.html

**Comment by dlenski** [comment]
Thanks! What did you need to change about the `vpnc-script` to get it working?

**Comment by 0atman** [comment]
Oh, just downloading it, as per your instructions! Not much of a faff really, though I was surprised it wasn't installed with the ubuntu packages. Does the licence of vpnc-script support bundling it in the repo / auto-downloading it?

**Comment by dlenski** [comment]
It should… you can also just use `apt install vpnc-script` to install the distro-default version.

(I personally don't ever use the default `vpnc-script`, but instead [vpn-slice](/dlenski/vpn-slice).)

**Comment by 0atman** [comment]
Yes, that didn't install it in the place I expected it on ubuntu 16.04

**Pull request merged**
